config/routes.rb
UnipeptWeb::Application.routes.draw do
  devise_for :users

  root :to => 'pages#home'

  resources :posts
  resources :dataset_items
  resources :sequences, :only => [:show, :index]
  resources :organisms, :only => [:show, :index]

  resources :datasets do
    collection do
      get 'database/:id' => 'datasets#preload', :defaults => { :type => 'database' }
      get 'pride/:id' => 'datasets#preload', :defaults => { :type => 'pride' }
    end
  end

  scope :private_api, as: 'private_api' do
    match "goterms", via: [:get, :post], :to => "private_api#goterms"
    match "ecnumbers",     via: [:get, :post], :to => "private_api#ecnumbers"
    match "taxa",     via: [:get, :post], :to => "private_api#taxa"
  end

  get '/search/sequence', :to => 'sequences#search', :as => 'sequence_search'

  scope :mpa, as: 'mpa' do
    match "/",        via: [:get, :post], :to => "mpa#analyze"
    match "pept2data", via: [:get, :post], :to => "mpa#pept2data"
  end

  get '/sequences/:id/:equate_il', :to => 'sequences#show', :as => 'sequence_show'
  get '/search/single', :to => 'search#single'

  match '/peptidome/sequences/:proteome_id.:format', via: [:get, :post], :to => 'peptidome#get_sequence_ids_for_proteome', :constraints => { :proteome_id => /[0-z\._]+/ }
  match '/peptidome/unique_sequences', via: [:get, :post], :to => 'peptidome#get_unique_sequences'
  match '/peptidome/full_sequences', via: [:get, :post], :to => 'peptidome#get_sequences'
  match '/peptidome/full_proteins', via: [:get, :post], :to => 'peptidome#get_proteins'
  match '/peptidome/convert_peptides', via: [:get, :post], :to => 'peptidome#convert_peptides'
  match '/peptidome/get_lca', via: [:get, :post], :to => 'peptidome#get_lca'
  get '/peptidome', :to => 'peptidome#analyze', :as => 'pancore_analyze'
  get '/pancore', :to => 'peptidome#analyze'
  get '/peptidefinder', :to => 'peptidome#analyze', :as => 'peptide_finder', defaults: { tab: 'peptidefinder' }
  get '/peptidomeclustering', :to => 'peptidome#analyze', :as => 'peptidome_clustering', defaults: { tab: 'peptidomeclustering' }

  get '/about',   :to => 'pages#about'
  get '/admin',   :to => 'pages#admin'
  get '/publications', :to => 'pages#publications'
  post '/mail',   :to => 'pages#mail'

  post "/convert", :to => "imagemagick#convert"

  post "/download", :to => "download#download"

  namespace :api, path: 'api/v1' do
    match 'pept2taxa' => "api#pept2taxa", via: [:get, :post]
    match 'pept2lca' => "api#pept2lca", via: [:get, :post]
    match 'taxa2lca' => 'api#taxa2lca', via: [:get, :post]
    match 'pept2prot' => 'api#pept2prot', via: [:get, :post]
    match 'taxonomy' => 'api#taxonomy', via: [:get, :post]
    match 'messages' => 'api#messages', via: [:get, :post]
  end

  namespace :api, path: "apidocs" do
    get "/",          :to => "apidocs#index",     :as => 'apidocs'
    get "pept2prot",  :to => "apidocs#pept2prot", :as => 'apidocs/pept2prot'
    get "pept2taxa",  :to => "apidocs#pept2taxa", :as => 'apidocs/pept2taxa'
    get "pept2lca",   :to => "apidocs#pept2lca",  :as => 'apidocs/pept2lca'
    get "taxa2lca",   :to => "apidocs#taxa2lca",  :as => 'apidocs/taxa2lca'
    get "taxonomy",   :to => "apidocs#taxonomy",  :as => 'apidocs/taxonomy'
  end

  namespace :api, path: "clidocs" do
    get "/",           :to => "clidocs#index",       :as => 'clidocs'
    get "casestudies", :to => "clidocs#casestudies", :as => 'clidocs/casestudies'
    get "casestudies/tpa", :to => "clidocs#casestudy_tpa", :as => 'clidocs/casestudy_tpa'
    get "casestudies/mpa", :to => "clidocs#casestudy_mpa", :as => 'clidocs/casestudy_mpa'
    get "casestudies/metagenomics", :to => "clidocs#casestudy_metagenomics", :as => 'clidocs/casestudy_metagenomics'
    get "prot2pept",   :to => "clidocs#prot2pept",   :as => 'clidocs/prot2pept'
    get "peptfilter",  :to => "clidocs#peptfilter",  :as => 'clidocs/peptfilter'
    get "uniprot",     :to => "clidocs#uniprot",     :as => 'clidocs/uniprot'
    get "pept2lca",    :to => "clidocs#pept2lca",    :as => 'clidocs/pept2lca'
    get "pept2prot",   :to => "clidocs#pept2prot",   :as => 'clidocs/pept2prot'
    get "pept2taxa",   :to => "clidocs#pept2taxa",   :as => 'clidocs/pept2taxa'
    get "taxa2lca",    :to => "clidocs#taxa2lca",    :as => 'clidocs/taxa2lca'
    get "taxonomy",    :to => "clidocs#taxonomy",    :as => 'clidocs/taxonomy'
  end

end

app/views/shared/_info_modal.html.erb
<div id='info-modal' class='modal fade modal-info' tabindex='-1'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class='modal-body'>
      </div>
    </div>
  </div>
</div>

app/views/shared/_load_datasets_form.html.erb
<div class='card card-nav datasets'>
  <div class='card-title card-title-colored'>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#database" data-toggle="tab">Sample data</a></li>
      <li><a href="#pride" data-toggle="tab">PRIDE</a></li>
    </ul>
  </div>
  <div class='card-supporting-text'>
    <div class="tab-content">
      <div class="tab-pane active" id="database">
        <%= render @datasets, :load => true, :edit => true %>
      </div>
      <div class="tab-pane" id="pride">
        <h3>Load data from the PRIDE archive</h3>
        <p>You can easily load data from the <a href="http://www.ebi.ac.uk/pride/" target="_blank">PRIDE</a> data repository. Simply enter an assay id (e.g. 8500) in the field below and click the 'Load PRIDE Dataset' button. The corresponding dataset will then be fetched using the PRIDE API and loaded into the search form on the left.</p>
        <div class="form-group">
          <label for="pride_exp_id">Assay id</label>
          <%= text_field_tag('pride_exp_id', nil, :placeholder => 'e.g. 8500', :class => "form-control")%>
        </div>
        <%= render 'pride_progress' %>
        <div class='search-buttons-centered'>
          <%= button_tag(raw("Load PRIDE dataset"), { :type => "button", :class => "load-pride btn btn-default" , :"data-loading-text" => "Loading..."}) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_multi_search_intro.html.erb
<div class="row search-info">
  <div class="col-xs-4 info-step">
    <h2>Enter a peptide list</h2>
    <p>
      Paste a list of peptides from your metaproteomics experiment in the search box. Each line should contain a single peptide.
    </p>
  </div>
  <div class="col-xs-4 info-step">
    <h2>Click search</h2>
    <p>
      Review the search settings for peptide deduplication, advanced missed cleavage handling and equating isoleucine and leucine before clicking search.
    </p>
  </div>
  <div class="col-xs-4 info-step">
    <h2>Gain insight</h2>
    <p>
      For each of the peptides, the lowest common ancestor (LCA) will be calculated, aggregated and visualised on the result page, giving you insight in the taxonomic diversity of your sample.
    </p>
  </div>
</div>

app/views/shared/_protein_search.html.erb
<%= form_tag(:protein_text_search, :method => "post", :class => "form-inline") do %>
    <%= text_area_tag(:q, "", :placeholder => "PROTEIN", :rows => 8, :cols => 50, :class => "form-control") %><br />
    <%= button_tag(raw("<span class='glyphicon glyphicon-search grow'></span> Search"), :type => "submit", :class => "btn btn-primary btn-animate") %>
<% end %>

app/views/shared/_protein_search_acc.html.erb
<%= form_tag(:protein_acc_search, :method => "get", :class => "form-inline") do %>
    <%= search_field_tag(:id, "", :placeholder => "UniProtKB accession nr", :class => "form-control") %>
    <%= button_tag(raw("<span class='glyphicon glyphicon-search grow'></span> Search"), :type => "submit", :class => "btn btn-primary btn-animate") %>
<% end %>

app/views/shared/_save_image_modal.html.erb
<div id='save-as-modal' class='modal fade' tabindex='-1'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class='modal-header'>
                <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                <div class="buttons text-center"></div>
            </div>
            <div class='modal-body'>
                <div class="image"></div>
            </div>
            <div class="modal-footer">
                If you use this figure in a publication, please cite: <br/>
                Mesuere et al. (2015) Proteomics <a href="https://doi.org/10.1002/pmic.201400361" target="_blank">doi:10.1002/pmic.201400361</a>
            </div>
        </div>
    </div>
</div>

app/views/shared/_sequence_ec_compare_search.html.erb
<%= form_tag(:sequence_ec_compare_search, :method => "post") do %>
  <div class="form-group">
    <label for="ecqs1">Paste sample 1</label>
    <%= text_area_tag(:ecqs1, nil, :rows => 7, :spellcheck => "false", :class => "form-control") %>
  </div>
  <div class="form-group">
    <label for="ecqs2">Paste sample 2</label>
    <%= text_area_tag(:ecqs2, nil, :rows => 7, :spellcheck => "false", :class => "form-control") %>
  </div>
  <div id="search_button">
    <%= button_tag(raw("<span class='glyphicon glyphicon-search'></span> Compare"), :type => "submit", :class => "btn btn-primary") %>
    <%= button_tag(raw("<span class='glyphicon glyphicon-repeat'></span> Start Over"), { :name => 'reset', :id => 'reset_button', :type => "reset", :class => "btn btn-default" }) %>
  </div>
<% end %>

app/views/shared/_sequence_ec_multi_search.html.erb
<%= form_tag(:sequence_ec_multi_search, :method => "post") do %>
  <div class="form-group">
    <label for="ecqs">Paste sample</label>
    <%= text_area_tag(:ecqs, nil, :rows => 7, :spellcheck => "false", :class => "form-control") %>
  </div>
  <div id="search_button">
    <%= button_tag(raw("<span class='glyphicon glyphicon-search'></span> Search"), :type => "submit", :class => "btn btn-primary") %>
    <%= button_tag(raw("<span class='glyphicon glyphicon-repeat'></span> Start Over"), { :name => 'reset', :id => 'reset_button', :type => "reset", :class => "btn btn-default" }) %>
  </div>
<% end %>

app/views/shared/_sequence_multi_search.html.erb
<div class='card'>
  <div class='card-title card-title-colored'>
    <h2 class='card-title-text'>Metaproteomics Analysis</h2>
  </div>
  <div class='card-supporting-text'>
    <%= form_tag(:mpa, :method => "post") do %>
      <div id="search_elements" class='form-group'>
        <label for="qs">Peptide list</label>
        <%= text_area_tag(:qs, nil, :rows => 7, :spellcheck => "false", :class => "form-control", autofocus: "true") %>
      </div>
      <div id="multisearch-warning" class='alert alert-warning' role='alert'><strong>Oh snap!</strong> You're trying to analyse <strong class="multisearch-warning-amount">a lot of</strong> peptides. Searching for this many peptides might take a while and the resulting visualisations will probably be suboptimal. Our <a href="<%= api_apidocs_path %>">webservices</a> are a great alternative.</div>
      <div class="form-group">
        <label for="search_name">Name this search <small class='secondary-text'>optional</small></label>
        <%= text_field_tag('search_name', nil, :placeholder => 'e.g. Sample B5', :class => "form-control js-has-focus-tooltip", title: "This name will be shown on the results page. Handy if you have many open tabs.")%>
      </div>
      <div class="checkbox">
        <%= label_tag(:il, check_box_tag(:il, 1, true) + " Equate I and L", title: "Equate isoleucine (I) and leucine (L) when matching peptides to UniProt entries.", class: 'js-has-hover-tooltip') %>
      </div>
      <div class="checkbox">
        <%= label_tag(:dupes, check_box_tag(:dupes, 1, true) + " Filter duplicate peptides", title: "Remove duplicate peptides from the input before searching.", class:'js-has-hover-tooltip') %>
      </div>
      <div class="checkbox">
        <%= label_tag(:missed, check_box_tag(:missed, 1, false) + " Advanced missed cleavage handling", title: "Recombine subpeptides of miscleavages. Enabling this has a serious performance impact!", class: 'js-has-hover-tooltip') %>
      </div>
      <div id="search_button" class='search-buttons-centered'>
        <%= button_tag(raw("<span class='glyphicon glyphicon-search grow'></span> Search"), :type => "submit", :class => "btn btn-primary btn-animate", :id =>"search-multi-form", :"data-loading-text" => "Loading...") %>
        <%= button_tag(raw("<span class='glyphicon glyphicon-repeat spin'></span> Start Over"), { :name => 'reset', :id => 'reset_button', :type => "reset", :class => "btn btn-default btn-animate" }) %>
      </div>
      <div id="form-progress" class="progress hide">
        <div class="progress-bar progress-bar-striped active"  role="progressbar" style="width: 100%">
          <span>Processing data...</span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_sequence_search.html.erb
<%= form_tag(:sequence_search, :method => "get", :class => "form-inline") do %>
  <%= search_field_tag(:q, "", :placeholder => "SEQUENCE", :class => "form-control", autofocus: true) %>
  <%= button_tag(raw("<span class='glyphicon glyphicon-search grow'></span> Search"), :type => "submit", :class => "btn btn-primary btn-animate") %>
  <div class="checkbox il-checkbox">
    <%= label_tag(:il_s, check_box_tag(:il_s, "equateIL", true) + " Equate I and L?") %>
  </div>
<% end %>

app/views/shared/_single_protein_search_intro.html.erb
<p>
  With protein analysis, you can submit a single <em>protein</em>. The application will respond with a list of all peptide records found in the protein along with a complete taxonomic lineage derived from the NCBI taxonomy. These lineages are presented as a comprehensible table and using an interactive tree view.
</p>